/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.tbd.tbd.gui;


import com.tbd.tbd.conexion.Conexion;
import com.tbd.tbd.usuarios.Usuario;
import java.awt.Color;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Jairo
 */
public class Login extends javax.swing.JFrame {
    
    private Connection c;
    private Usuario usr;
    
    private int mouseX, mouseY;
    public Login() {
        initComponents();
        incLbl.setVisible(false);
        usr = new Usuario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        bg2 = new javax.swing.JPanel();
        loginPanel = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        userTextBox = new javax.swing.JTextField();
        userLabel = new javax.swing.JLabel();
        contLabel = new javax.swing.JLabel();
        separator1 = new javax.swing.JSeparator();
        separator2 = new javax.swing.JSeparator();
        contTextBox = new javax.swing.JPasswordField();
        login = new javax.swing.JPanel();
        botonLogin = new javax.swing.JLabel();
        ojoPanel = new javax.swing.JPanel();
        ojo = new javax.swing.JLabel();
        incLbl = new javax.swing.JLabel();
        close = new javax.swing.JPanel();
        botonClose = new javax.swing.JLabel();
        bar = new javax.swing.JPanel();
        exitB = new javax.swing.JPanel();
        exitLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        bg.setBackground(new java.awt.Color(237, 241, 214));
        bg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bg.setPreferredSize(new java.awt.Dimension(737, 467));

        bg2.setBackground(new java.awt.Color(31, 31, 31));

        loginPanel.setBackground(new java.awt.Color(255, 255, 255));

        title.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Login");

        userTextBox.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        userTextBox.setForeground(new java.awt.Color(204, 204, 204));
        userTextBox.setText("Usuario");
        userTextBox.setBorder(null);
        userTextBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userTextBoxFocusGained(evt);
            }
        });
        userTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTextBoxActionPerformed(evt);
            }
        });
        userTextBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                userTextBoxKeyTyped(evt);
            }
        });

        userLabel.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        userLabel.setText("Usuario");

        contLabel.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        contLabel.setText("Contraseña");

        separator1.setForeground(new java.awt.Color(0, 0, 0));

        separator2.setForeground(new java.awt.Color(0, 0, 0));

        contTextBox.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        contTextBox.setForeground(new java.awt.Color(204, 204, 204));
        contTextBox.setText("Contraseña maestra");
        contTextBox.setBorder(null);
        contTextBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                contTextBoxFocusGained(evt);
            }
        });
        contTextBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                contTextBoxKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contTextBoxKeyTyped(evt);
            }
        });

        login.setBackground(new java.awt.Color(255, 255, 255));
        login.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        login.setName(""); // NOI18N
        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginMouseEntered(evt);
            }
        });

        botonLogin.setBackground(new java.awt.Color(157, 192, 139));
        botonLogin.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        botonLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botonLogin.setText("Login");
        botonLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonLoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonLoginMouseExited(evt);
            }
        });

        javax.swing.GroupLayout loginLayout = new javax.swing.GroupLayout(login);
        login.setLayout(loginLayout);
        loginLayout.setHorizontalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
        );
        loginLayout.setVerticalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        ojoPanel.setBackground(new java.awt.Color(255, 255, 255));

        ojo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ojo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ojo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ojoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ojoMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout ojoPanelLayout = new javax.swing.GroupLayout(ojoPanel);
        ojoPanel.setLayout(ojoPanelLayout);
        ojoPanelLayout.setHorizontalGroup(
            ojoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ojo, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
        );
        ojoPanelLayout.setVerticalGroup(
            ojoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ojo, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        incLbl.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        incLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        incLbl.setText("Usuario o Contraseña incorrectos");

        close.setBackground(new java.awt.Color(255, 255, 255));
        close.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        close.setName(""); // NOI18N
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
        });

        botonClose.setBackground(new java.awt.Color(157, 192, 139));
        botonClose.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        botonClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botonClose.setText("Close");
        botonClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonCloseMouseExited(evt);
            }
        });

        javax.swing.GroupLayout closeLayout = new javax.swing.GroupLayout(close);
        close.setLayout(closeLayout);
        closeLayout.setHorizontalGroup(
            closeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonClose, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
        );
        closeLayout.setVerticalGroup(
            closeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonClose, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                        .addGap(0, 22, Short.MAX_VALUE)
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(loginPanelLayout.createSequentialGroup()
                                .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(contLabel)
                            .addComponent(userLabel)
                            .addComponent(userTextBox)
                            .addComponent(separator1)
                            .addComponent(separator2)
                            .addGroup(loginPanelLayout.createSequentialGroup()
                                .addComponent(contTextBox, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ojoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29))))
            .addComponent(incLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(incLbl)
                .addGap(17, 17, 17)
                .addComponent(userLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(separator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(contLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(contTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ojoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout bg2Layout = new javax.swing.GroupLayout(bg2);
        bg2.setLayout(bg2Layout);
        bg2Layout.setHorizontalGroup(
            bg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg2Layout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(207, Short.MAX_VALUE))
        );
        bg2Layout.setVerticalGroup(
            bg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(loginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(50, 50, 50))
        );

        bar.setBackground(new java.awt.Color(237, 241, 214));
        bar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barMouseDragged(evt);
            }
        });
        bar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barMousePressed(evt);
            }
        });

        exitB.setBackground(new java.awt.Color(237, 241, 214));
        exitB.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        exitB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitBMouseExited(evt);
            }
        });

        exitLbl.setBackground(new java.awt.Color(237, 241, 214));
        exitLbl.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        exitLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitLbl.setText("X");
        exitLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitLblMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitBLayout = new javax.swing.GroupLayout(exitB);
        exitB.setLayout(exitBLayout);
        exitBLayout.setHorizontalGroup(
            exitBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );
        exitBLayout.setVerticalGroup(
            exitBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout barLayout = new javax.swing.GroupLayout(bar);
        bar.setLayout(barLayout);
        barLayout.setHorizontalGroup(
            barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        barLayout.setVerticalGroup(
            barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barLayout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addComponent(exitB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(bg2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addComponent(bar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                .addComponent(bar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bg2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 747, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userTextBoxActionPerformed

    private void barMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barMousePressed
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_barMousePressed

    private void barMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - mouseX , y - mouseY );
    }//GEN-LAST:event_barMouseDragged

    private void exitLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLblMouseClicked
         
        this.dispose();
        
    }//GEN-LAST:event_exitLblMouseClicked

    private void exitLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLblMouseEntered
        exitB.setBackground(new Color(210, 51, 105));
    }//GEN-LAST:event_exitLblMouseEntered

    private void exitBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBMouseExited
        exitB.setBackground(new Color(203, 182, 184));
    }//GEN-LAST:event_exitBMouseExited

    private void botonLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonLoginMouseEntered
       // botonDesb.setBackground(new Color(223, 202, 204));
    }//GEN-LAST:event_botonLoginMouseEntered

    private void loginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseEntered
        
    }//GEN-LAST:event_loginMouseEntered

    private void exitBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBMouseEntered
        //exitB.setBackground(new Color(210, 51, 105));
    }//GEN-LAST:event_exitBMouseEntered

    private void exitLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLblMouseExited
        exitB.setBackground(new Color(237,241,214));
    }//GEN-LAST:event_exitLblMouseExited

    private void botonLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonLoginMouseExited
//        botonDesb.setBackground(new Color(203, 182, 184));
    }//GEN-LAST:event_botonLoginMouseExited

    private void userTextBoxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userTextBoxFocusGained
        
        if(userTextBox.getText().equals("Usuario")){
            userTextBox.setText("");
        }
        
        userTextBox.setForeground(Color.BLACK);
        if(String.valueOf(contTextBox.getPassword()).equals("Contraseña maestra")||String.valueOf(contTextBox.getPassword()).equals("")){
           contTextBox.setText("Contraseña maestra");
           contTextBox.setForeground(Color.gray);
        }
        
        //incLbl.setVisible(false);
        
    }//GEN-LAST:event_userTextBoxFocusGained

    private void contTextBoxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contTextBoxFocusGained
        
        if(String.valueOf(contTextBox.getPassword()).equals("Contraseña maestra")){
            contTextBox.setText("");
            contTextBox.setForeground(Color.BLACK);
        }
        
        if(String.valueOf(userTextBox.getText()).equals("Usuario")||String.valueOf(userTextBox.getText()).equals("")){
           userTextBox.setText("Usuario");
           userTextBox.setForeground(Color.gray);
        }
        //incLbl.setVisible(false);
        
    }//GEN-LAST:event_contTextBoxFocusGained

    private void ojoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ojoMousePressed
        contTextBox.setEchoChar((char)0);
    }//GEN-LAST:event_ojoMousePressed

    private void ojoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ojoMouseReleased
        contTextBox.setEchoChar('*');
    }//GEN-LAST:event_ojoMouseReleased

    private void botonLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonLoginMouseClicked
        VentanaIU ventana;
        try {
            ResultSet rs;
            int pid;
          
            c = Conexion.getConnection();
            
            CallableStatement stmnt = c.prepareCall("SELECT * FROM login(?,?) AS (pid INT4, usr INT4, sesion INT4)");
            
            stmnt.setString(1, userTextBox.getText());
            stmnt.setString(2,String.valueOf(contTextBox.getPassword()));
            
            stmnt.execute();
            rs = stmnt.getResultSet();
            
            if(rs.next()){
                pid = rs.getInt("pid");
            }else{
                pid = -1;
            }
            
            if(pid > 0){
                incLbl.setText("Login Exitoso PID: " + pid);
                usr.setIdUsr(rs.getInt("usr"));
                usr.setIdSesion(rs.getInt("sesion"));
                
                
            
                ventana = new VentanaIU(usr, c);
                ventana.setVisible(true);
                
            }else{
                incLbl.setText("Login Fallido");
        
            }
            
            incLbl.setVisible(true);
            
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botonLoginMouseClicked

    private void contTextBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contTextBoxKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_contTextBoxKeyPressed

    private void userTextBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userTextBoxKeyTyped
        incLbl.setVisible(false);
    }//GEN-LAST:event_userTextBoxKeyTyped

    private void contTextBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contTextBoxKeyTyped
        incLbl.setVisible(false);
    }//GEN-LAST:event_contTextBoxKeyTyped

    private void botonCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCloseMouseClicked
        if(usr.valido()){
            
             try {

                CallableStatement stmnt = c.prepareCall("SELECT close(?,?)");

                stmnt.setInt(1, usr.getIdUsr());
                stmnt.setInt(2, usr.getIdSesion());

                stmnt.execute();

                c.close();
                
                usr.setIdUsr(-1);
                usr.setIdSesion(-1);
                
                incLbl.setText("Sesión cerrada");
                
            } catch (SQLException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }  
        }
    }//GEN-LAST:event_botonCloseMouseClicked

    private void botonCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCloseMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_botonCloseMouseEntered

    private void botonCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCloseMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_botonCloseMouseExited

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_closeMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bar;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel bg2;
    private javax.swing.JLabel botonClose;
    private javax.swing.JLabel botonLogin;
    private javax.swing.JPanel close;
    private javax.swing.JLabel contLabel;
    private javax.swing.JPasswordField contTextBox;
    private javax.swing.JPanel exitB;
    private javax.swing.JLabel exitLbl;
    private javax.swing.JLabel incLbl;
    private javax.swing.JPanel login;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JLabel ojo;
    private javax.swing.JPanel ojoPanel;
    private javax.swing.JSeparator separator1;
    private javax.swing.JSeparator separator2;
    private javax.swing.JLabel title;
    private javax.swing.JLabel userLabel;
    private javax.swing.JTextField userTextBox;
    // End of variables declaration//GEN-END:variables
}
