package com.tbd.tbd.gui;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */




import com.tbd.tbd.usuarios.Usuario;
import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Jairo
 */
public class VentanaRegistroComp extends javax.swing.JFrame {

   
    private Usuario usr;
    private Connection c;
    private ArrayList<File> imagenes;
    private int mouseX, mouseY;
    
    public VentanaRegistroComp(Usuario usr, Connection c) {
        setLookAndFeel();
        initComponents();
        this.usr = usr;
        this.c = c;
        imagenes = new ArrayList<>();
        cargarVentana();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        bar = new javax.swing.JPanel();
        exitB = new javax.swing.JPanel();
        exitLbl = new javax.swing.JLabel();
        recPanel = new javax.swing.JPanel();
        recLbl = new javax.swing.JLabel();
        msjLbl = new javax.swing.JLabel();
        bg2 = new javax.swing.JPanel();
        aceptarBtn = new javax.swing.JPanel();
        aceptarLbl = new javax.swing.JLabel();
        registroLbl = new javax.swing.JLabel();
        ramTxtBox = new javax.swing.JTextField();
        nPerfiLbl = new javax.swing.JPanel();
        nPerifBtn = new javax.swing.JLabel();
        marcaTxtBox = new javax.swing.JTextField();
        ramLbl = new javax.swing.JLabel();
        capacLbl = new javax.swing.JLabel();
        imgSP = new javax.swing.JScrollPane();
        imgTab = new javax.swing.JTable();
        perifLbl = new javax.swing.JLabel();
        perifSP = new javax.swing.JScrollPane();
        perifTab = new javax.swing.JTable();
        nImgBtn = new javax.swing.JPanel();
        nImgLbl = new javax.swing.JLabel();
        imgLbl = new javax.swing.JLabel();
        ramLbl1 = new javax.swing.JLabel();
        capacDispTxtBox = new javax.swing.JTextField();
        quitPerifBtn = new javax.swing.JPanel();
        nPerifBtn2 = new javax.swing.JLabel();
        quitImgBtn = new javax.swing.JPanel();
        nPerifBtn3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        bg.setBackground(new java.awt.Color(237, 241, 214));
        bg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bg.setPreferredSize(new java.awt.Dimension(737, 467));

        bar.setBackground(new java.awt.Color(237, 241, 214));
        bar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barMouseDragged(evt);
            }
        });
        bar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barMousePressed(evt);
            }
        });

        exitB.setBackground(new java.awt.Color(237, 241, 214));
        exitB.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        exitB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitBMouseExited(evt);
            }
        });

        exitLbl.setBackground(new java.awt.Color(237, 241, 214));
        exitLbl.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        exitLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitLbl.setText("X");
        exitLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitLblMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitBLayout = new javax.swing.GroupLayout(exitB);
        exitB.setLayout(exitBLayout);
        exitBLayout.setHorizontalGroup(
            exitBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exitBLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exitLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        exitBLayout.setVerticalGroup(
            exitBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        recPanel.setBackground(new java.awt.Color(237, 241, 214));
        recPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        recPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                recPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                recPanelMouseExited(evt);
            }
        });

        recLbl.setBackground(new java.awt.Color(237, 241, 214));
        recLbl.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        recLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        recLbl.setText("R");
        recLbl.setToolTipText("");
        recLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        recLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                recLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                recLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                recLblMouseExited(evt);
            }
        });

        javax.swing.GroupLayout recPanelLayout = new javax.swing.GroupLayout(recPanel);
        recPanel.setLayout(recPanelLayout);
        recPanelLayout.setHorizontalGroup(
            recPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(recLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );
        recPanelLayout.setVerticalGroup(
            recPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(recLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        msjLbl.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        msjLbl.setText("Registro Exitoso");
        msjLbl.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                msjLblMouseMoved(evt);
            }
        });

        javax.swing.GroupLayout barLayout = new javax.swing.GroupLayout(bar);
        bar.setLayout(barLayout);
        barLayout.setHorizontalGroup(
            barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(msjLbl)
                .addGap(227, 227, 227)
                .addComponent(recPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(exitB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        barLayout.setVerticalGroup(
            barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exitB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(recPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(msjLbl, javax.swing.GroupLayout.Alignment.TRAILING)))
        );

        bg2.setBackground(new java.awt.Color(31, 31, 31));

        aceptarBtn.setBackground(new java.awt.Color(255, 255, 255));

        aceptarLbl.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        aceptarLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        aceptarLbl.setText("Aceptar");
        aceptarLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        aceptarLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aceptarLblMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout aceptarBtnLayout = new javax.swing.GroupLayout(aceptarBtn);
        aceptarBtn.setLayout(aceptarBtnLayout);
        aceptarBtnLayout.setHorizontalGroup(
            aceptarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(aceptarLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
        );
        aceptarBtnLayout.setVerticalGroup(
            aceptarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(aceptarLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        );

        registroLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        registroLbl.setForeground(new java.awt.Color(255, 255, 255));
        registroLbl.setText("REGISTRO DE COMPUTADORA");

        ramTxtBox.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        ramTxtBox.setForeground(new java.awt.Color(204, 204, 204));
        ramTxtBox.setText("RAM");
        ramTxtBox.setBorder(null);
        ramTxtBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ramTxtBoxFocusGained(evt);
            }
        });
        ramTxtBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ramTxtBoxActionPerformed(evt);
            }
        });

        nPerfiLbl.setBackground(new java.awt.Color(255, 255, 255));

        nPerifBtn.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        nPerifBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nPerifBtn.setText("Nuevo");
        nPerifBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nPerifBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nPerifBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout nPerfiLblLayout = new javax.swing.GroupLayout(nPerfiLbl);
        nPerfiLbl.setLayout(nPerfiLblLayout);
        nPerfiLblLayout.setHorizontalGroup(
            nPerfiLblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nPerifBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
        );
        nPerfiLblLayout.setVerticalGroup(
            nPerfiLblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nPerifBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        );

        marcaTxtBox.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        marcaTxtBox.setForeground(new java.awt.Color(204, 204, 204));
        marcaTxtBox.setText("MARCA");
        marcaTxtBox.setBorder(null);
        marcaTxtBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                marcaTxtBoxFocusGained(evt);
            }
        });
        marcaTxtBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marcaTxtBoxActionPerformed(evt);
            }
        });

        ramLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ramLbl.setForeground(new java.awt.Color(255, 255, 255));
        ramLbl.setText("RAM:");

        capacLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        capacLbl.setForeground(new java.awt.Color(255, 255, 255));
        capacLbl.setText("CAPACIDAD:");

        imgTab.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        imgTab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Imagen", "Descripcion(Opcional)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        imgTab.setFocusable(false);
        imgTab.setGridColor(new java.awt.Color(167, 167, 167));
        imgTab.setRowHeight(30);
        imgTab.setSelectionBackground(new java.awt.Color(147, 147, 147));
        imgTab.setSelectionForeground(new java.awt.Color(255, 255, 255));
        imgTab.setShowHorizontalLines(true);
        imgTab.getTableHeader().setReorderingAllowed(false);
        imgSP.setViewportView(imgTab);
        if (imgTab.getColumnModel().getColumnCount() > 0) {
            imgTab.getColumnModel().getColumn(0).setResizable(false);
            imgTab.getColumnModel().getColumn(1).setResizable(false);
        }

        perifLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        perifLbl.setForeground(new java.awt.Color(255, 255, 255));
        perifLbl.setText("PERIFÉRICOS:");

        perifTab.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        perifTab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Periferico", "Marca"
            }
        ));
        perifTab.setFocusable(false);
        perifTab.setGridColor(new java.awt.Color(167, 167, 167));
        perifTab.setRowHeight(30);
        perifTab.setSelectionBackground(new java.awt.Color(147, 147, 147));
        perifTab.setSelectionForeground(new java.awt.Color(255, 255, 255));
        perifTab.setShowHorizontalLines(true);
        perifTab.getTableHeader().setReorderingAllowed(false);
        perifSP.setViewportView(perifTab);
        if (perifTab.getColumnModel().getColumnCount() > 0) {
            perifTab.getColumnModel().getColumn(0).setResizable(false);
            perifTab.getColumnModel().getColumn(1).setResizable(false);
            perifTab.getColumnModel().getColumn(1).setHeaderValue("Marca");
        }

        nImgBtn.setBackground(new java.awt.Color(255, 255, 255));

        nImgLbl.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        nImgLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nImgLbl.setText("Nueva");
        nImgLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nImgLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nImgLblMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout nImgBtnLayout = new javax.swing.GroupLayout(nImgBtn);
        nImgBtn.setLayout(nImgBtnLayout);
        nImgBtnLayout.setHorizontalGroup(
            nImgBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nImgLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
        );
        nImgBtnLayout.setVerticalGroup(
            nImgBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nImgLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        );

        imgLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        imgLbl.setForeground(new java.awt.Color(255, 255, 255));
        imgLbl.setText("IMÁGENES:");

        ramLbl1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ramLbl1.setForeground(new java.awt.Color(255, 255, 255));
        ramLbl1.setText("MARCA:");

        capacDispTxtBox.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        capacDispTxtBox.setForeground(new java.awt.Color(204, 204, 204));
        capacDispTxtBox.setText("CAPACIDAD");
        capacDispTxtBox.setBorder(null);
        capacDispTxtBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                capacDispTxtBoxFocusGained(evt);
            }
        });
        capacDispTxtBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capacDispTxtBoxActionPerformed(evt);
            }
        });

        quitPerifBtn.setBackground(new java.awt.Color(255, 255, 255));

        nPerifBtn2.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        nPerifBtn2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nPerifBtn2.setText("Quitar");
        nPerifBtn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nPerifBtn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nPerifBtn2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout quitPerifBtnLayout = new javax.swing.GroupLayout(quitPerifBtn);
        quitPerifBtn.setLayout(quitPerifBtnLayout);
        quitPerifBtnLayout.setHorizontalGroup(
            quitPerifBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nPerifBtn2, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
        );
        quitPerifBtnLayout.setVerticalGroup(
            quitPerifBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nPerifBtn2, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        );

        quitImgBtn.setBackground(new java.awt.Color(255, 255, 255));

        nPerifBtn3.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        nPerifBtn3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nPerifBtn3.setText("Quitar");
        nPerifBtn3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nPerifBtn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nPerifBtn3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout quitImgBtnLayout = new javax.swing.GroupLayout(quitImgBtn);
        quitImgBtn.setLayout(quitImgBtnLayout);
        quitImgBtnLayout.setHorizontalGroup(
            quitImgBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nPerifBtn3, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
        );
        quitImgBtnLayout.setVerticalGroup(
            quitImgBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nPerifBtn3, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout bg2Layout = new javax.swing.GroupLayout(bg2);
        bg2.setLayout(bg2Layout);
        bg2Layout.setHorizontalGroup(
            bg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg2Layout.createSequentialGroup()
                .addGroup(bg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(bg2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(quitPerifBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nPerfiLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bg2Layout.createSequentialGroup()
                        .addGroup(bg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bg2Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(bg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(perifLbl)
                                    .addComponent(registroLbl)
                                    .addComponent(perifSP, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(bg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(bg2Layout.createSequentialGroup()
                                            .addComponent(quitImgBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(nImgBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(imgSP, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(aceptarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(imgLbl)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bg2Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(bg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(capacLbl)
                                    .addComponent(ramLbl)
                                    .addComponent(ramLbl1))
                                .addGap(46, 46, 46)
                                .addGroup(bg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ramTxtBox)
                                    .addComponent(capacDispTxtBox)
                                    .addComponent(marcaTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        bg2Layout.setVerticalGroup(
            bg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(registroLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ramLbl)
                    .addComponent(ramTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(capacDispTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(capacLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(marcaTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ramLbl1))
                .addGap(9, 9, 9)
                .addComponent(perifLbl)
                .addGap(18, 18, 18)
                .addComponent(perifSP, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nPerfiLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quitPerifBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(imgLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imgSP, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nImgBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quitImgBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(aceptarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(bg2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                .addComponent(bar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bg2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 754, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void barMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barMousePressed
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_barMousePressed

    private void barMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - mouseX , y - mouseY );
    }//GEN-LAST:event_barMouseDragged

    private void exitLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLblMouseClicked
        this.dispose();
    }//GEN-LAST:event_exitLblMouseClicked

    private void exitLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLblMouseEntered
        exitB.setBackground(new Color(210, 51, 105));
    }//GEN-LAST:event_exitLblMouseEntered

    private void exitBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBMouseExited
        exitB.setBackground(new Color(203, 182, 184));
    }//GEN-LAST:event_exitBMouseExited

    private void exitBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBMouseEntered
        exitB.setBackground(new Color(210, 51, 105));
    }//GEN-LAST:event_exitBMouseEntered

    private void exitLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLblMouseExited
        exitB.setBackground(new Color(237,241,214));
    }//GEN-LAST:event_exitLblMouseExited

    private void recLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recLblMouseClicked
        cargarVentana();
    }//GEN-LAST:event_recLblMouseClicked

    private void recLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recLblMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_recLblMouseEntered

    private void recLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recLblMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_recLblMouseExited

    private void recPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recPanelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_recPanelMouseEntered

    private void recPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recPanelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_recPanelMouseExited

    private void nPerifBtn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nPerifBtn2MouseClicked
        int fila;
        
        fila = perifTab.getSelectedRow();
        
        if(fila >= 0){
            DefaultTableModel modelo;
            modelo  = (DefaultTableModel) perifTab.getModel();
            modelo.removeRow(fila);
        }
        
        
    }//GEN-LAST:event_nPerifBtn2MouseClicked

    private void capacDispTxtBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capacDispTxtBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_capacDispTxtBoxActionPerformed

    private void capacDispTxtBoxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_capacDispTxtBoxFocusGained
        capacDispTxtBox.setForeground(Color.black);
    }//GEN-LAST:event_capacDispTxtBoxFocusGained

    private void nImgLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nImgLblMouseClicked
        JFileChooser fc = new JFileChooser();
        int seleccion = fc.showOpenDialog(this);

        if(seleccion == JFileChooser.APPROVE_OPTION){
            File fichero = fc.getSelectedFile();

            insertImg(fichero);
        }
    }//GEN-LAST:event_nImgLblMouseClicked

    private void marcaTxtBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marcaTxtBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marcaTxtBoxActionPerformed

    private void marcaTxtBoxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_marcaTxtBoxFocusGained
        marcaTxtBox.setForeground(Color.black);
    }//GEN-LAST:event_marcaTxtBoxFocusGained

    private void nPerifBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nPerifBtnMouseClicked
        DefaultTableModel modelo;
        Object[]          fila;
        modelo  = (DefaultTableModel) perifTab.getModel();
        fila = new Object[2];
        fila[0] = "";
        fila[1] = "";
        modelo.addRow(fila);
    }//GEN-LAST:event_nPerifBtnMouseClicked

    private void ramTxtBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ramTxtBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ramTxtBoxActionPerformed

    private void ramTxtBoxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ramTxtBoxFocusGained
        ramTxtBox.setForeground(Color.black);
    }//GEN-LAST:event_ramTxtBoxFocusGained

    private void aceptarLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aceptarLblMouseClicked
        int filasP, filasF, idC;
        CallableStatement stmnt;
        ResultSet rs;

        filasP = perifTab.getRowCount();
        filasF = imgTab.getRowCount();

        if(filasF > 0 && filasP > 0){
            try{

                stmnt = c.prepareCall("SELECT regComp(?,?,?)");
                stmnt.setInt(1, Integer.parseInt(ramTxtBox.getText()));
                stmnt.setInt(2, Integer.parseInt(capacDispTxtBox.getText()));
                stmnt.setString(3, marcaTxtBox.getText());

                stmnt.execute();

                rs = stmnt.getResultSet();

                if(rs.next()){
                    idC = rs.getInt(1);

                    for(int i = 0 ; i < filasP ; i++){
                        stmnt = c.prepareCall("SELECT regPerifCompu(?,?,?)");
                        stmnt.setString(1, (String)perifTab.getValueAt(i, 0));
                        stmnt.setString(2, (String)perifTab.getValueAt(i, 1));
                        stmnt.setInt(3, idC);
                        stmnt.execute();
                    }

                    for(int i = 0; i < filasF; i++){
                        stmnt = c.prepareCall("SELECT * FROM regFotoCompu(?,?,?)");
                        stmnt.setBinaryStream(1, convertImgFis(imagenes.get(i)), (int) imagenes.get(i).length());
                        stmnt.setString(2, (String)imgTab.getValueAt(i, 1));
                        stmnt.setInt(3, idC);
                        stmnt.execute();
                    }
                }

                msjLbl.setVisible(true);
            }catch (SQLException ex) {
                ex.printStackTrace();
            }
        }

    }//GEN-LAST:event_aceptarLblMouseClicked

    private void nPerifBtn3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nPerifBtn3MouseClicked
        int fila;
        
        fila = imgTab.getSelectedRow();
        
        if(fila >= 0){
            DefaultTableModel modelo;
            modelo  = (DefaultTableModel) imgTab.getModel();
            modelo.removeRow(fila);
            imagenes.remove(fila);
        }
    }//GEN-LAST:event_nPerifBtn3MouseClicked

    private void msjLblMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_msjLblMouseMoved
        if(msjLbl.isVisible()){
            int segundos = 1; // Tiempo en segundos
            try {
                Thread.sleep(segundos * 1000); // El argumento se expresa en milisegundos, por lo que se multiplica por 1000
                msjLbl.setVisible(false);
            } catch (InterruptedException ex) {
                Thread.currentThread().interrupt();
            }
            this.dispose();
        }
    }//GEN-LAST:event_msjLblMouseMoved

    public void insertImg(File img){
        DefaultTableModel modelo;
        Object[]          fila;
        
        if(img != null){
            imagenes.add(img);
           
            modelo  = (DefaultTableModel) imgTab.getModel();
            fila = new Object[2];
            fila[0] = img.getPath();
            fila[1] = "";
            modelo.addRow(fila);
        }
    }
    
    private byte[] convertImgBytea(File img){
        byte [] data;
        BufferedImage bufferimage;
        
        data = null;
            try {
                bufferimage = ImageIO.read(img);
                ByteArrayOutputStream output = new ByteArrayOutputStream();
                ImageIO.write(bufferimage, "jpg", output );
                data = output.toByteArray();


            } catch (IOException ex) {
                ex.printStackTrace();
            }
            
        return data;
    }
    
    private FileInputStream convertImgFis(File img){
        FileInputStream fis;
        
        fis = null;
        
        try {
            fis = new FileInputStream(img);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(VentanaRegistroComp.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return fis;
    }
    
    private void clearPerifTab(){
        DefaultTableModel modelo;
        modelo  = (DefaultTableModel) perifTab.getModel();
        modelo.setRowCount(0);
    }
    
    private void clearImgTab(){
        DefaultTableModel modelo;
        modelo  = (DefaultTableModel) imgTab.getModel();
        modelo.setRowCount(0);
    }
    
    private void cargarVentana(){
        clearPerifTab();
        clearImgTab();
        msjLbl.setVisible(false);
    }
    
    private void setLookAndFeel(){
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroComp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroComp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroComp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroComp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel aceptarBtn;
    private javax.swing.JLabel aceptarLbl;
    private javax.swing.JPanel bar;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel bg2;
    private javax.swing.JTextField capacDispTxtBox;
    private javax.swing.JLabel capacLbl;
    private javax.swing.JPanel exitB;
    private javax.swing.JLabel exitLbl;
    private javax.swing.JLabel imgLbl;
    private javax.swing.JScrollPane imgSP;
    private javax.swing.JTable imgTab;
    private javax.swing.JTextField marcaTxtBox;
    private javax.swing.JLabel msjLbl;
    private javax.swing.JPanel nImgBtn;
    private javax.swing.JLabel nImgLbl;
    private javax.swing.JPanel nPerfiLbl;
    private javax.swing.JPanel nPerfiLbl1;
    private javax.swing.JLabel nPerifBtn;
    private javax.swing.JLabel nPerifBtn1;
    private javax.swing.JLabel nPerifBtn2;
    private javax.swing.JLabel nPerifBtn3;
    private javax.swing.JLabel perifLbl;
    private javax.swing.JScrollPane perifSP;
    private javax.swing.JTable perifTab;
    private javax.swing.JPanel quitImgBtn;
    private javax.swing.JPanel quitPerifBtn;
    private javax.swing.JLabel ramLbl;
    private javax.swing.JLabel ramLbl1;
    private javax.swing.JTextField ramTxtBox;
    private javax.swing.JLabel recLbl;
    private javax.swing.JPanel recPanel;
    private javax.swing.JLabel registroLbl;
    // End of variables declaration//GEN-END:variables
}
